config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'top#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show]

  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/views/shared/_navigation.html.erb
<header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span><%= link_to "Oustagram", root_path, class: "navbar-brand" %></span>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to 'Photo投稿', new_post_path %></li>
                    <% if user_signed_in? %>
                        <li><%= link_to "マイベージ", user_path(current_user.id) %></li>
                        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                    <% else %>
                        <li><%= link_to "ログイン", new_user_session_path %></li>
                        <li><%= link_to "サインアップ", new_user_registration_path %></li>
                    <% end %>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</header>