config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'top#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show]

  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  mount_uploader :image, ImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_params, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.user_id = current_user.id
    @post.save
    flash[:success] = '投稿しました！！'
    redirect_to posts_path
  end

  def edit
  end

  def update
    @post.update(posts_params)
    flash[:success] = '更新しました！！'
    redirect_to posts_path
  end

  def destroy
    @post.destroy
    flash[:success] = '削除しました！！'
    redirect_to posts_path
  end

  private

    def posts_params
      params.require(:post).permit(:content, :image, :image_cache)
    end

    def set_params
      @post = Post.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_img(post)
    if post.image?
      img_url = post.image
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url)
  end
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
    <%= post_img(post) if post_img(post) %>
    <%= f.file_field :image, class: 'btn btn-info btn-block' %>
    <br>
    <%= f.hidden_field :image_cache %>
    <%= f.text_area :content, size: '70x5', class: 'form-control', placeholder: "内容" %>
    <%= f.submit '投稿', class: 'btn btn-primary', data: { confirm: 'よろしいですか？' } %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
        <h1>投稿を編集する</h1>
        <%= render 'form', post: @post %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="container">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
        <% @posts.each do |post| %>
            <div class="posts">
                <div class="username-header">
                    <span><%= post.created_at.to_s(:human) %></span>
                    <div class="post-avatar">
                        <%= profile_img(post.user) %>
                    </div>
                    <div class="username">
                        <strong><%= link_to "#{post.user.name}", user_path(post.user.id), style: "color:black;" %></strong>
                    </div>
                </div>
                <div class="photo-posts">
                    <%= post_img(post) %>
                </div>
                <div class="content-posts">
                    <strong><%= post.user.name %></strong>
                    <br>
                    <%= simple_format(post.content) %>
                    <span><%= link_to '編集', edit_post_path(post.id), class: 'btn-sm btn-info' %><%= link_to '削除', post_path(post.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？'}, class: 'btn-sm btn-danger' %></span>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
        <h1>Photo投稿</h1>
        <%= render 'form', post: @post %>
    </div>
</div>